# Generated by Django 4.2 on 2024-01-01 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_website_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.website'),
        ),
    ]
