# Generated by Django 4.2 on 2024-01-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staffmember_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
