# Generated by Django 4.2 on 2024-01-01 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_website_is_success'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='website',
            name='request_id',
        ),
        migrations.AddField(
            model_name='website',
            name='request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.scraprequest'),
            preserve_default=False,
        ),
    ]
