# Generated by Django 4.2 on 2024-01-01 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_scraprequest_remove_website_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.scraprequest'),
        ),
    ]
